### ISSUE TITLE
Extend for privacy options

### ISSUE THREAD

**Issue by kroppenstedt** [palasthotel/grid-wordpress-box-social#10]
Hey @EdwardBock, 

we need some options to load the Boxes on User request and not per default. Please extend the box to keep this adjustable. 

Ref: OSN#421

**Comment by EdwardBock** [comment]
@kroppenstedt 

First try for facebook privacy button is working.

**Comment by EdwardBock** [comment]
@kroppenstedt 

Let's talk about this again tomorrow. Facebook is ready to be private.
