### ISSUE TITLE
Improve UX for Boxes

### ISSUE THREAD

**Issue by benthebear** [palasthotel/grid-wordpress-box-social#2]
@EdwardBock  …

The UX of the Social Boxes could be improved some …
## Settings:

![bildschirmfoto 2016-06-16 um 08 20 14](https://cloud.githubusercontent.com/assets/49137/16107230/4b46b994-339b-11e6-89ce-2320d48bcd1a.png)
- We might add a sentence here, where to find these Credentials
- And the "string(4) "none" obviously should be more selfexplaining
## Name of the Boxes

![bildschirmfoto 2016-06-16 um 08 20 39](https://cloud.githubusercontent.com/assets/49137/16107251/7482c046-339b-11e6-8977-fcbbb098d92c.png)

fb_like_box is not all to selfexplaining …

**Comment by EdwardBock** [comment]
I'll plan more time to improve UX for Grid. I promise ;)

**Comment by EdwardBock** [comment]
UX is improved. Have a look at the latest version 1.4

**Comment by benthebear** [comment]
Nice.
