### ISSUE TITLE
Error in getting FacebookResponse->decodedBody

### ISSUE THREAD

**Issue by philippze** [palasthotel/grid-wordpress-box-social#4]
Hi Palasthotel!

There's a mean little error that results in message "No Facebook posts found" instead of the expected feed. Here's the fix:

https://github.com/philippze/grid-wordpress-box-social/commit/3caa024ba43f12e5f3b71f8db4307d0e234cb9c0

Schöne Grüße!
Philipp

**Comment by mkernel** [comment]
d'oh. Do you mind creating a pull request for this?

**Comment by philippze** [comment]
Yes, I can! Do you mind if I include everything else I've changed yesterday? This is:

- I've added a composer file, so you can just add the git repo and the say `composer require philippze/grid-social-boxes` to install the plugin (I would change the name to `palasthotel/grid-social-boxes`). Instead, one could install `wpackagist-plugin/grid-social-boxes` with composer, but as the git repo is much better than what's on wordpress.org, I prefer to have the composer file here as well.
- I've made it possible that we override the HTML that's used to display a facebook post with the theme file `grid/facebook-post.tpl.php`.
- I've allowed that we configure what fields the plugin will fetch from facebook with the constnat `GRID_FACEBOOK_FIELDS`.

**Comment by mkernel** [comment]
Sounds great - i'll have a look once the pull request is landed :)

**Comment by EdwardBock** [comment]
@mkernel 

I had to debug here anyway so I looked into the request. Looked good to me. :)
